# Generated by Django 4.2 on 2025-02-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
